[package]
name = "libstd"
version = "0.1.0"
authors = ["Connor Horman <chorman64@gmail.com>"]
edition = "2018"
license = "BSD+Patent"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
which = {version="4.1.0",path="../stdlib-deps/which-rs"}
target-tuples = {version="0.2.2",path="../stdlib-deps/rust-target-tuples"}
