[package]
name = "xlang_targets"
version = "0.1.0"
authors = ["Connor Horman <chorman64@gmail.com>"]
edition = "2018"
license = "BSD-2-Clause-Patent"
description = """
ABI Safe Interfaces for target triples and discovering compiler-required information about targets
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
target-tuples = "0.5.5"
xlang_abi = {path="../xlang_abi",version="0.2.0"}
