name: C/C++ CI Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_clang:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.0
      with:
        submodules: true 
    - name: Install packages
      run: sudo apt-get install ninja-build ccache
      
    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")
    
    - name: ccache cache files
      uses: actions/cache@v1.1.0
      with:
          path: ${{github.workspace}}/.ccache
          key: ${{matrix.config.name}}-ccache-clang-${{steps.ccache_cache_timestamp.outputs.timestamp}}
          restore-keys: |
           ${{matrix.config.name}}-ccache-clang-
        
    - name: Clang Build
      uses: LightningCreations/action-cmake-build@v1.2
      with:
        # C Compiler for toolchain
        cc: clang # optional
        # C++ Compiler for toolchain
        cxx: clang++ # optional
        update-submodules: true
        parallel: 8
        build-dir: ${{github.workspace}}/build-clang 
        build-type: Release
        configure-options: -GNinja -DLLVM_CCACHE_BUILD=ON -DLLVM_CCACHE_DIR=${{github.workspace}}/.ccache -DLLVM_APPEND_VC_REV=OFF -DLLVM_PARALLEL_LINK_JOBS=2
  build_gcc:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.0
      with:
        submodules: true 
    - name: Install packages
      run: sudo apt-get install ninja-build ccache
      
    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")
    
    - name: ccache cache files
      uses: actions/cache@v1.1.0
      with:
          path: ${{github.workspace}}/.ccache
          key: ${{matrix.config.name}}-ccache-gcc-${{steps.ccache_cache_timestamp.outputs.timestamp}}
          restore-keys: |
           ${{matrix.config.name}}-ccache-gcc-
        
    - name: GCC Build
      uses: LightningCreations/action-cmake-build@v1.2
      with:
        # C Compiler for toolchain
        cc: gcc # optional
        # C++ Compiler for toolchain
        cxx: g++ # optional
        update-submodules: true
        parallel: 8
        build-dir: ${{github.workspace}}/build-gcc 
        build-type: Release
        configure-options: -GNinja -DLLVM_CCACHE_BUILD=ON -DLLVM_CCACHE_DIR=${{github.workspace}}/.ccache -DLLVM_APPEND_VC_REV=OFF -DLLVM_PARALLEL_LINK_JOBS=2
